#!/bin/bash
set -euo pipefail

# Generates the agent-guard.rb Homebrew cask file.
# Usage: ./scripts/build-cask.sh <version> <sha256>
# Output: cask file content to stdout

if [ $# -ne 2 ]; then
  echo "Usage: $0 <version> <sha256>" >&2
  echo "Example: $0 1.3.0 abc123..." >&2
  exit 1
fi

VERSION="$1"
SHA256="$2"

cat <<EOF
# THIS FILE IS GENERATED BY scripts/build-cask.sh. DO NOT EDIT.
cask "agent-guard" do
  version "$VERSION"
  sha256 "$SHA256"

  url "https://github.com/naufalafif/agent-guard/releases/download/v#{version}/AgentGuard.zip"
  name "AgentGuard"
  desc "macOS menu bar security scanner for MCP servers and AI agent skills"
  homepage "https://github.com/naufalafif/agent-guard"

  depends_on macos: ">= :ventura"

  app "AgentGuard.app"

  postflight do
    # App auto-installs scanners on first launch, but try to pre-install via uv if available
    system_command "/bin/bash", args: ["-lc", "command -v uv && uv tool install cisco-ai-mcp-scanner 2>/dev/null; true"]
    system_command "/bin/bash", args: ["-lc", "command -v uv && uv tool install cisco-ai-skill-scanner 2>/dev/null; true"]
  end

  zap trash: [
    "~/.cache/mcp-scan",
    "~/.config/mcp-scan",
  ]

  caveats <<~EOS
    AgentGuard has been installed to /Applications.

    Open it from Spotlight or:
      open /Applications/AgentGuard.app

    The app auto-installs mcp-scanner and skill-scanner on first launch.

    To launch at login:
      Open AgentGuard > Settings > Launch at login
  EOS
end
EOF
